---
- name: Install Docker and Docker Compose
  hosts: all
  become: yes
  tasks:
    # - name: Install required system packages
    #   package:
    #     name: "{{ item }}"
    #     state: present
    #   loop:
    #     - apt-transport-https
    #     - ca-certificates
    #     - curl
    #     - gnupg-agent
    #     - software-properties-common
    #   when: ansible_os_family == "Debian"

    # - name: Add Docker GPG key
    #   apt_key:
    #     url: https://download.docker.com/linux/ubuntu/gpg
    #     state: present
    #   when: ansible_os_family == "Debian"

    # - name: Add Docker repository
    #   apt_repository:
    #     repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
    #     state: present
    #   when: ansible_os_family == "Debian"

    # - name: Update apt package cache
    #   apt:
    #     update_cache: yes
    #   when: ansible_os_family == "Debian"

    # - name: Install Docker CE
    #   apt:
    #     name: docker-ce
    #     state: present
    #   when: ansible_os_family == "Debian"

    # - name: Create pip configuration directory
    #   file:
    #     path: "{{ ansible_env.HOME }}/.config/pip"
    #     state: directory

    # - name: Set pip index URL to a normal source
      # copy:
      #   dest: "{{ ansible_env.HOME }}/.config/pip/pip.conf"
      #   content: |
      #     [global]
      #     index-url = https://pypi.org/simple
      #     trusted-host = pypi.org
      #                   pypi.python.org
      #                   files.pythonhosted.org
      # become: yes
      # delegate_to: localhost

    - name: Install Docker Compose
      pip:
        name: docker-compose
        state: present
