---
- name: Install pyenv on CentOS/Ubuntu
  hosts: all
  become: yes
  tasks:

    - name: Clone pyenv repository
      git:
        repo: https://kkgithub.com/pyenv/pyenv.git
        dest: ~/.pyenv
        update: no

    - name: Append PATH variable to .bashrc
      lineinfile:
        path: ~/.bashrc
        line: "export PATH=\"$HOME/.pyenv/bin:$PATH\""
        create: yes
      register: path_added

    - name: Evaluate pyenv initialization in .bashrc
      lineinfile:
        path: ~/.bashrc
        line: "eval \"$(pyenv init --path)\""
        insertafter: "^export PATH="
        create: yes
      when: path_added is changed

    - name: Source .bashrc to apply changes
      command: "bash -c 'source ~/.bashrc'"
      when: path_added is changed

    - name: Verify pyenv installation
      command: "pyenv --version"
      # command: "bash -c 'pyenv --version'"

