- name: Prepare packages for yum
  yum:
    name:
      - epel-release
      - sysstat
      - git
      - bash-completion
      - bind-utils
      - jq
      - htop
      - lsof
      - rsync
  ignore_errors: true
  when: ansible_os_family == 'RedHat'

- name: Prepare packages for apt
  apt:
    pkg:
      - sysstat
      - git
      - bash-completion
      - bind-utils
      - jq
      - htop
      - lsof
      - rsync
  ignore_errors: true
  when: ansible_os_family == 'Debian'

- name: set -o vi
  lineinfile:
    path: ~/.bashrc
    regexp: "^set -o vi$"
    line: "set -o vi"

- name: C-l -> clear
  lineinfile:
    path: ~/.bashrc
    regexp: "clear-screen"
    line: bind -m vi-insert "\C-l":clear-screen

- name: LANG=
  lineinfile:
    path: ~/.bashrc
    regexp: "export LANG"
    line: export LANG=''
