- name: add yum utils
  yum:
    name: yum-utils
    state: latest

- name: add docker repo -> aliyun
  shell: yum-config-manager --add-repo http://mirrors.aliyun.com/docker-ce/linux/centos/docker-ce.repo
  when: ansible_date_time.tz_offset == "+0800"

- name: add docker repo -> offical
  shell: yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
  when: ansible_date_time.tz_offset != "+0800"

- name: download docker ce
  yum:
    name: docker-ce
    state: latest
